apiVersion: v1
kind: Service
metadata:
  name: cart-redis
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cart-redis
subsets:
- addresses:
  - ip: 10.40.14.74
  ports:
  - name: http
    port: 6379
    protocol: TCP
