apiVersion: v1
kind: Service
metadata:
  name: catalog-mongo
  labels:
    app: acmefit
    service: catalog-db
spec:
  ports:
    - port: 27017
      name: mongo-catalog
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: catalog-mongo
subsets:
- addresses:
  - ip: 10.40.14.80
  ports:
  - name: http
    port: 27017
    protocol: TCP
