apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: echo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.10
        name: echo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo-system
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echo
  type: LoadBalancer

