apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: tkg-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: echo
  namespace: tkg-system
subsets:
- addresses:
  - ip: ${SERVICE_CLUSTER_NODE_IP}
  ports:
  - name: http
    port: 80
    protocol: TCP

