apiVersion: v1
kind: Service
metadata:
  name: users-redis
  labels:
    app: acmefit
    service: users-redis
spec:
  ports:
    - port: 6379
      name: mongo-users
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: users-redis
subsets:
- addresses:
  - ip: 10.40.14.79
  ports:
  - name: http
    port: 6379
    protocol: TCP      
